@clientId=secure-api-client
# from keycloak client credentials interface
@clientSecret=EeNCvstsBLdJoBefaQuq7C8o0SBQwgTL

### enable OIDC in Kong
# instrospection is mandatory to be able to validate the token
POST http://localhost:8001/routes/quarkus-route/plugins
Content-Type: application/json

{
    "name": "oidc",
    "config": {
        "discovery": "http://192.168.1.42:8090/realms/secure-api/.well-known/openid-configuration",
        "introspection_endpoint": "http://192.168.1.42:8090/realms/secure-api/protocol/openid-connect/token/introspect",
        "client_id": "{{clientId}}",
        "client_secret": "{{clientSecret}}",
        "bearer_only": "yes",
        "realm": "secure-api",
        "scope": "openid",
        "revoke_tokens_on_logout": "yes",
        "disable_userinfo_header": "yes",
        "disable_id_token_header": "yes",
        "disable_access_token_header": "yes"
    }
}

### get token
# @name generateToken
# endpoint is allowed by 'Standard Token Exchange' authentication method
# the testuser account must be fully defined (email verified, no arequired actions, ....
POST http://localhost:8090/realms/secure-api/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{base64Encode admin:admin}}

grant_type=password
&client_id={{clientId}}
&client_secret={{clientSecret}}
&username=testuser
&password=test123

###

@accessToken = {{generateToken.response.body.$.access_token}}

### call secured api
GET http://localhost:8000/quarkus-api/api/users/me
Authorization: Bearer {{accessToken}}

### direct call secured api
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}

### call api
GET http://localhost:8000/quarkus-api/api/greets
Authorization: Bearer {{accessToken}}

### call second api
GET http://localhost:8000/quarkus-api/api/propagate
Authorization: Bearer {{accessToken}}
